dataX["inconsistentStoriesIntro"] = {
  name: "Introduction: Inconsistent Stories",
  descriptionTemplate: "inconsistentStoriesDescription",
  nextTemplate: "scaffold",
  nextType: "inconsistentStoriesScaffold",
       
  examples: [
    {
      exampleTemplate: "inconsistentStoriesExample",
      headline: "Study: Firstborn Children Have More Ambition",
      headlineId: "35964",
      description: "",
      hasDescription: "false",
      voice: "<span class='focusPoint'>I like to think that I have equally</span> <span class='focusPoint2'>low expectations</span> of all my children.",
      voice_img: "voice1md2.jpg",
      annotation1: "I like to think that I have equally... ", 
      annotation2: "...low expectations..", 
      annotation3: "The speaker is a <span class='focusPoint0'>good parent</span>,<br> he treats his children equally, you expect his to stay he has equally high expectations of them", 
      annotation4: "The speaker is a <span class='focusPoint0'>bad parent</span>,<br> he has low expectations of his children", 
    },
    {
      exampleTemplate: "inconsistentStoriesExample",
      headline: "FDA Bans E-Cigarettes For Minors",
      headlineId: "35876",
      description: "",
      hasDescription: "false",
      voice: "<span class='focusPoint'>This is just another case of Big Government</span> exercising its <span class='focusPoint2'>legitimate Constitutional power</span> to regulate the sale of products as set out in the Commerce Clause.",
      voice_img: "voice1md2.jpg",
      annotation1: "This is just another case of Big Government... ", 
      annotation2: "...legitimate Constitutional power ...", 
      annotation3: "This is <span class='focusPoint0'>bad</span>. <br> We expect this to indicate the government is like overextending it's power.", 
      annotation4: "This is <span class='focusPoint0'>good</span>. <br>The government is totally within it's power. ", 
    }, 
    {
      exampleTemplate: "inconsistentStoriesExample",
      headline: "New York Times’ Editor Fired",
      headlineId: "36047",
      description: "New York Times chairman Arthur Sulzberger Jr. announced Wednesday he’s replacing Executive Editor Jill Abramson, the paper’s first female newsroom chief, in a move media insiders say may have to do with Abramson questioning her salary level as compared to her male predecessors’. ",
      hasDescription: "true",
      voice: "<span class='focusPoint'>This is an inspirational story for all women</span> who hope to one day rise to one of the most prestigious positions in their industry <span class='focusPoint2'>only to be fired from it under questionable circumstances</span>.",
      voice_img: "voice1md2.jpg",
      annotation1: "This is an inspirational story for all women... ", 
      annotation2: "...only to be fired from it under questionable circumstances.", 
      annotation3: "This is <span class='focusPoint0'>good</span>,<br> it is an inspirational story", 
      annotation4: "This is <span class='focusPoint0'>bad </span>,<br> something unfair probably happened.", 
    }, 
    {
      exampleTemplate: "inconsistentStoriesExample",
      headline: "People Bending iPhones At Apple Stores",
      headlineId: "37064",
      description: "",
      hasDescription: "false",
      voice: "<span class='focusPoint'>I can’t believe people would</span> just walk into an Apple store and start breaking things <span class='focusPoint2'>like it’s a Best Buy.</span>",
      voice_img: "voice1md2.jpg",
      annotation1: "I can’t believe people would... ", 
      annotation2: "...like it’s a Best Buy.", 
      annotation3: "This is <span class='focusPoint0'>bad</span>,<br> because breaking things is bad", 
      annotation4: "This is <span class='focusPoint0'>bad </span>,<br> breaking things at Apple Stores is bad, but it's fine at other stores.", 
    },     
    {
      exampleTemplate: "inconsistentStoriesExample",
      headline: "Study: Women Threatened By Peers Wearing Red",
      headlineId: "36466",
      description: "",
      hasDescription: "true",
      voice: "<span class='focusPoint'>Isn’t that just like a woman</span> to be subtly influenced by the unconscious evolutionary cues that <span class='focusPoint2'>affect us all</span>.",
      voice_img: "voice1md2.jpg",
      annotation1: "Isn’t that just like a woman... ", 
      annotation2: "...affect us all.", 
      annotation3: "This <span class='focusPoint0'>blames women </span>,<br> for feeling threatened by red", 
      annotation4: "This indicates that everyone is suspectible <span class='focusPoint0'>not just women </span>,<br>.", 
    }, 

    {
      exampleTemplate: "inconsistentStoriesExample",
      headline: "Florida School To Stop Giving Kids Mountain Dew Before Tests",
      headlineId: "35888",
      description: "",
      hasDescription: "false",
      voice: "<span class='focusPoint'>That’s bullshit.</span> Mountain Dew is supposed to be <span class='focusPoint2'>given afterwards as a reward for doing well.</span>",
      voice_img: "voice1md2.jpg",
      annotation1: "That’s bullshit.", 
      annotation2: "...given afterwards as a reward for doing well.", 
      annotation3: "This is <span class='focusPoint0'>bad</span>,<br> because Mt. Dew is bad for kids", 
      annotation4: "This is <span class='focusPoint0'>bad </span>,<br> because Mt. Dew should be given to kids, but only after.", 
    }, 
  ]   
}
  
dataX["inconsistentStoriesScaffold"] = {
  name: "Practice: Identifying Inconsistent Stories",
  descriptionTemplate: "inconsistentStoriesScaffoldDescription",
  nextTemplate: "exercise",
  nextType: "inconsistentStoriesExercise",
  
  examples: [
    {
      exampleTemplate: "inconsistentStoriesScaffold",
      headline: "NBC, Netflix Cancel Bill Cosby’s Return To TV Amid Rape Allegations",
      headlineId: "37502",
      description: "After decades-old allegations resurfaced and more women came forward this week with new accusations that comedian Bill Cosby had drugged and sexually assaulted them, NBC and Netflix announced they were canceling in-development projects with the 77-year-old comic, including a stand-up special and a new sitcom that was to be his long-awaited return to television.",
      hasDescription: "true",
      voice: "<span class='focusPoint'>Whenever you’re on top, 15 women will always try to take you down</span> with <span class='focusPoint2'>frighteningly similar tales </span> of sexual assault.",
      voice_img: "voice1md2.jpg",
      annotation1: "Whenever you’re on top, 15 women will always try to take you down...", 
      annotation2: "...frighteningly similar tales...", 
      annotation3: "This is sympathizes with <span class='focusPoint0'>Bill Cosby</span>,<br> and blames the women", 
      annotation4: "This is sympathizes with <span class='focusPoint0'>the women </span>,<br> and blames Bill Cosby.", 
    }, 
    {
      exampleTemplate: "inconsistentStoriesScaffold",
      headline: "NBC, Netflix Cancel Bill Cosby’s Return To TV Amid Rape Allegations",
      headlineId: "37502",
      description: "After decades-old allegations resurfaced and more women came forward this week with new accusations that comedian Bill Cosby had drugged and sexually assaulted them, NBC and Netflix announced they were canceling in-development projects with the 77-year-old comic, including a stand-up special and a new sitcom that was to be his long-awaited return to television.",
      hasDescription: "true",
      voice: "<span class='focusPoint'>It’s a shame</span> a dozen or so allegations can put an end to what would have been a <span class='focusPoint2'>very lackluster comeback</span>.",
      voice_img: "voice1md2.jpg",
      annotation1: "It’s a shame...", 
      annotation2: "...very lackluster comeback.", 
      annotation3: "The <span class='focusPoint0'>rape allegations</span> are bad.", 
      annotation4: "The <span class='focusPoint0'>comeback</span> is going to be bad.", 
    },
    {
      exampleTemplate: "inconsistentStoriesScaffold",
      headline: "NBC, Netflix Cancel Bill Cosby’s Return To TV Amid Rape Allegations",
      headlineId: "37502",
      description: "After decades-old allegations resurfaced and more women came forward this week with new accusations that comedian Bill Cosby had drugged and sexually assaulted them, NBC and Netflix announced they were canceling in-development projects with the 77-year-old comic, including a stand-up special and a new sitcom that was to be his long-awaited return to television.",
      hasDescription: "true",
      voice: "This goes to show that <span class='focusPoint'>even celebrities can’t get away with something</span> like that <span class='focusPoint2'>for more than 30 or 40 years</span>.",
      voice_img: "voice1md2.jpg",
      annotation1: "...even celebrities can’t get away with something...", 
      annotation2: "...for more than 30 or 40 years.", 
      annotation3: "This is <span class='focusPoint0'>good</span>, <br>because celebrities can't get away with thing forever.", 
      annotation4: "This is <span class='focusPoint0'>bad</span>,<br> because celebrities basically can't get away with thing forever (or at least a really long time.", 
    },
    {
      exampleTemplate: "inconsistentStoriesScaffold",
      headline: "Study: Firstborn Children Have More Ambition",
      headlineId: "35964",
      description: "",
      hasDescription: "false",
      voice: "<span class='focusPoint'>As a second-born girl, I’d just like to say</span> <span class='focusPoint2'> wooooo! Spring break!</span>",
      voice_img: "voice1md2.jpg",
      annotation1: "As a second-born girl, I’d just like to say...", 
      annotation2: "...wooooo! Spring break!.", 
      annotation3: "This is <span class='focusPoint0'>false</span>,<br> second-born kids are not all bad", 
      annotation4: "This is <span class='focusPoint0'>true </span>,<br> this second-born child is an airhead.", 
    },
    {
      exampleTemplate: "inconsistentStoriesScaffold",
      headline: "Florida School To Stop Giving Kids Mountain Dew Before Tests",
      headlineId: "35888",
      description: "",
      hasDescription: "false",
      voice: "<span class='focusPoint'>That’s bullshit.</span> Mountain Dew is supposed to be <span class='focusPoint2'>given afterwards as a reward for doing well.</span>",
      voice_img: "voice1md2.jpg",
      annotation1: "That’s bullshit.", 
      annotation2: "...given afterwards as a reward for doing well.", 
      annotation3: "This is <span class='focusPoint0'>bad</span>,<br> because Mt. Dew is bad for kids.", 
      annotation4: "This is <span class='focusPoint0'>bad </span>,<br> because Mt. Dew should be given to kids, but only after.", 
    },
    {
      exampleTemplate: "inconsistentStoriesScaffold",
      headline: "Obama Faces Backlash For ‘Beverage Salute’",
      headlineId: "35888",
      description: "President Obama faced backlash on Twitter after stepping out of Air Force One yesterday and saluting Marines with a Styrofoam cup in his right hand when his arms were full, which many have called disrespectful.",
      hasDescription: "false",
      voice: "<span class='focusPoint'>The commander-in-chief should know better than anyone </span>that <span class='focusPoint2'>you only raise a Styrofoam coffee cup when saluting the Air Force. For the Marines, it’s a Dasani bottle.</span>",
      voice_img: "voice1md2.jpg",
      annotation1: "The commander-in-chief should know better than anyone... ", 
      annotation2: "...you only raise a Styrofoam coffee cup when saluting the Air Force. For the Marines, it’s a Dasani bottle.", 
      annotation3: "This is <span class='focusPoint0'>bad</span>,<br> because Obama should not have saluted with a styrofoam cup.", 
      annotation4: "This is <span class='focusPoint0'>bad </span>,<br> ecause Obama should not have saluted <i>the Marines</i>with a styrofoam cup", 
    },    
    {
      exampleTemplate: "inconsistentStoriesScaffold",
      headline: "George Clooney Engaged",
      headlineId: "37007",
      description: "People magazine is reporting that after a string of high-profile relationships, 52-year-old actor George Clooney has popped the question to his girlfriend of less than a year, British-Lebanese human rights lawyer Amal Alamuddin.",
      hasDescription: "false",
      voice: "<span class='focusPoint'>Men always start settling</span> for <span class='focusPoint2'>beautiful, intelligent women</span> after they turn 50.",
      voice_img: "voice1md2.jpg",
      annotation1: "Men always start settling... (after they turn 50).", 
      annotation2: "...beautiful, intelligent women.", 
      annotation3: "He is marrying her because he's 50 and finally willing to settle <br>(a <span class='focusPoint0'>bad</span> reason).", 
      annotation4: "He is marrying her because she's beautiful and intelligent. <br>(a <span class='focusPoint0'>good</span> reason)", 
    },    
  ]
}
  
dataX["inconsistentStoriesExercise"] = {
    name: "Exercise: Writing Inconsistent Stories",
    descriptionTemplate: "inconsistentStoriesExerciseInstructions",
    nextTemplate: "introduction",
    nextType: "detailsIntro",
    examples: [
      
      {
        exampleTemplate: "inconsistentStoriesExercise",
        headline: "",
        headlineId: "headline1",
        description: "description",
        voice: "So all I have to do to get fresh deer meat is pretend I’m homeless?",
        annotation1: "Teens",
        annotation2: "Parents of teens",
        annotation3: ""
      },
      {
        exampleTemplate: "inconsistentStoriesExercise",
        headline: "60 Teens Arrested In Senior Class Prank",
        headlineId: "headline2",
        description: "",
        voice: "By failing to uphold the values of Teaneck High School, the only people those teens were really pranking were themselves.",
        annotation1: "Senior Class",
        annotation2: "High School Principle, other responsible adult"
      },
      {
        exampleTemplate: "inconsistentStoriesExercise",
        headline: "Study: Dads Who Do Dishes Have More Ambitious Daughters",
        headlineId: "headline3",
        description: "descriptionXXXX",
        voice: "That would explain my daughter’s uncontrollable thirst for power.",
        annotation1: "Dads",
        annotation2: "Dad"
      },
      {
        exampleTemplate: "inconsistentStoriesExercise",
        headline: "‘Mighty Morphin Power Rangers’ Movie In The Works",
        headlineId: "headline4",
        description: "",
        voice: "So are they going to be dinosaur Zords or jungle animal Zords? Fucking tell me now!",
        annotation1: "‘Mighty Morphin Power Rangers’",
        annotation2: "obsessive fan of ‘Mighty Morphin Power Rangers’"
      },        
    ]    
    
  }